/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package swdesign;

import swdesign.examplegames.stupidnumbergame.StupidNumberGame;
import swdesign.examplegames.stupidnumbergame.StupidNumberPlayer;
import swdesign.examplegames.stupidnumbergame.players.ConstantPlayer;
import swdesign.examplegames.stupidnumbergame.players.RandomPlayer;
import swdesign.game.Game;
import swdesign.gameListeners.ITournamentListener;
import swdesign.gameListeners.TournamentEvent;
import swdesign.tournament.ParticipantInfo;
import swdesign.tournament.Tournament;

/**
 *
 * @author adamv_000
 */
public class Test extends javax.swing.JFrame implements ITournamentListener {

    /**
     * Creates new form Test
     */
    public Test() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Test");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jButton1)
                .addContainerGap(269, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jButton1)
                .addContainerGap(223, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Runtime runtime = Runtime.getRuntime();
        Tournament<StupidNumberPlayer> tournament = new Tournament(runtime.availableProcessors());
        tournament.addListener(this);
        Game game = new StupidNumberGame(10);
        StupidNumberPlayer[] players = new StupidNumberPlayer[7];

        StupidNumberPlayer a = new RandomPlayer("a", "a", 10, 20);
        StupidNumberPlayer b = new RandomPlayer("b", "b", 90, 180);
        StupidNumberPlayer c = new RandomPlayer("c", "c", 8, 120);
        StupidNumberPlayer d = new RandomPlayer("d", "d", 7, 200);
        StupidNumberPlayer e = new RandomPlayer("e", "e", 6, 89);
        StupidNumberPlayer z = new RandomPlayer("z", "z", 5, 47);
        StupidNumberPlayer h = new RandomPlayer("h", "h", 5, 47);
       
        players[0] = (a);
        players[1] = (b);
        players[2] = (c);
        players[3] = (d);
        players[4] = (e);
        players[5] = (z);
        players[6] = (h);

        tournament.tournamentStart(game, players);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Test().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void gameUpdate(TournamentEvent event) {
        if (event.getType() != TournamentEvent.TYPE_TOURNAMENT_ENDED) {
            System.out.println("Message: " + event.getMessage());
        } else {
            for (ParticipantInfo participantInfo : event.getParticipants()) {
                System.out.println("Name: " + participantInfo.getName() + " score: " + participantInfo.getScore());
            }
        }
    }
}
